// src/contacts/resourcesCotentinAnnuaire.js

export const resourcesCotentinAnnuaire = [

{
id: "annuaire_had_cotentin",
label: "HAD Cotentin",
type: "HAD",
territory: ["Cotentin"],
categories: ["hospitalisation", "domicile"],
keywords: ["had", "soins à domicile"],
contact: {
phone: "02 33 XX XX XX",
email: ""
},
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_ssr_valognes",
label: "SSR Valognes",
type: "SSR",
territory: ["Cotentin"],
categories: ["rééducation"],
keywords: ["ssr", "rééducation"],
contact: {
phone: "",
email: ""
},
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_usp_valognes",
label: "USP Valognes",
type: "USP",
territory: ["Cotentin"],
categories: ["soins palliatifs"],
keywords: ["usp", "palliatif"],
contact: {
phone: "",
email: ""
},
platform: {
url: "https://extranet.ch-cotentin.fr/preadusp/"
},
note: "",
source: "annuaire"
},

{
id: "annuaire_clinique_cotentin",
label: "Clinique du Cotentin",
type: "Clinique",
territory: ["Cotentin"],
categories: ["hospitalisation"],
keywords: ["clinique"],
contact: {
phone: "",
email: ""
},
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_ehpad_cotentin",
label: "EHPAD Cotentin",
type: "EHPAD",
territory: ["Cotentin"],
categories: ["hébergement"],
keywords: ["ehpad", "personne âgée"],
contact: {
phone: "",
email: ""
},
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_ssr_chbourg",
label: "SSR Cherbourg",
type: "SSR",
territory: ["Cotentin"],
categories: ["rééducation"],
keywords: ["ssr", "rééducation"],
contact: { phone: "", email: "" },
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_had_normandie",
label: "HAD Normandie",
type: "HAD",
territory: ["Normandie"],
categories: ["domicile"],
keywords: ["had", "soins domicile"],
contact: { phone: "", email: "" },
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_emsp",
label: "EMSP Cotentin",
type: "Equipe mobile",
territory: ["Cotentin"],
categories: ["palliatif"],
keywords: ["emsp", "douleur", "fin de vie"],
contact: { phone: "", email: "" },
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_dac_cotentin",
label: "DAC Cotentin",
type: "Coordination",
territory: ["Cotentin"],
categories: ["coordination"],
keywords: ["dac", "parcours", "coordination"],
contact: { phone: "", email: "" },
platform: {
url: "https://www.normandie-dac.fr"
},
note: "",
source: "annuaire"
},

{
id: "annuaire_clc",
label: "CLIC Cotentin",
type: "Social",
territory: ["Cotentin"],
categories: ["gérontologie"],
keywords: ["clic", "personne âgée"],
contact: { phone: "", email: "" },
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_service_social_hopital",
label: "Service social hospitalier",
type: "Social",
territory: ["Cotentin"],
categories: ["accompagnement"],
keywords: ["assistant social"],
contact: { phone: "", email: "" },
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_spasad",
label: "SPASAD Cotentin",
type: "Aide à domicile",
territory: ["Cotentin"],
categories: ["domicile"],
keywords: ["spasad", "aide domicile"],
contact: { phone: "", email: "" },
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_siad",
label: "SIAD Cotentin",
type: "Aide à domicile",
territory: ["Cotentin"],
categories: ["soins domicile"],
keywords: ["siad", "infirmier domicile"],
contact: { phone: "", email: "" },
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_portage_repas",
label: "Portage de repas",
type: "Service",
territory: ["Cotentin"],
categories: ["domicile"],
keywords: ["repas", "livraison"],
contact: { phone: "", email: "" },
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_telealarme",
label: "Téléalarme",
type: "Service",
territory: ["Cotentin"],
categories: ["sécurité"],
keywords: ["telealarme", "chute"],
contact: { phone: "", email: "" },
platform: null,
note: "",
source: "annuaire"
},
{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_bourdon_stephanie_touati_karim",
name: "Cabinet BOURDON Stéphanie / TOUATI Karim",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "1 rue de Bassigny, 50100 Cherbourg-en-Cotentin",
phone: "02 33 22 27 62",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_cauchard_herve_rabec_gaetan_seve",
name: "Cabinet CAUCHARD Hervé / RABEC Gaëtan / SEVENOU Sophie",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "Allée du Fort, 50100 Cherbourg-en-Cotentin",
phone: "02 33 93 87 15",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_colasse_sylvie_loubradou_julie_l",
name: "Cabinet COLASSE Sylvie / LOUBRADOU Julie / LUCBERT Nathalie / MENDY Marie-France / MITTERAND Charlotte / PICOT Lise / SOPHIE Léa",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "76 rue Emmanuel-Liais, 50100 Cherbourg-en-Cotentin",
phone: "02 33 53 23 23 / 02 33 93 54 25",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_corbin_emilie_garnier_helene",
name: "Cabinet CORBIN Émilie / GARNIER Hélène",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "5 rue Thomas-Henry, 50100 Cherbourg-en-Cotentin",
phone: "06 86 35 17 59",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_vasselin_karine_vincent_lise",
name: "Cabinet VASSELIN Karine / VINCENT Lise",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "101 rue du Val-de-Saire, 50100 Cherbourg-en-Cotentin",
phone: "02 33 44 57 36",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_deganne_caroline_lecostey_laetit",
name: "Cabinet DEGANNE Caroline / LECOSTEY Laetitia / MARIE Didier",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "68 avenue de Normandie, 50100 Cherbourg-en-Cotentin",
phone: "02 33 41 09 11",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},
{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_helard_daniel_marti_isabelle",
name: "Cabinet HÉLARD Daniel / MARTI Isabelle",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "22 rue du Val-de-Saire, 50100 Cherbourg-en-Cotentin",
phone: "02 33 43 21 63",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_demont_julie_jeuland_marlene",
name: "Cabinet DEMONT Julie / JEULAND Marlène",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "14 avenue de Normandie, 50100 Cherbourg-en-Cotentin",
phone: "02 33 01 08 60 / 06 62 36 08 60",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_deschamps_morgane_picot_marie_fr",
name: "Cabinet DESCHAMPS Morgane / PICOT Marie-Françoise / SANSON Aurélie / SEYER Ophélie",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "10 rue Christine, 50100 Cherbourg-en-Cotentin",
phone: "02 33 93 16 49",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_despierres_vincent_rose_melanie",
name: "Cabinet DESPIERRES Vincent / ROSE Mélanie",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "145 avenue de Paris, 50100 Cherbourg-en-Cotentin",
phone: "02 33 43 18 95",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_douasbin_nathalie_mouchel_caroli",
name: "Cabinet DOUASBIN Nathalie / MOUCHEL Caroline",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "2 rue Contant, 50100 Cherbourg-en-Cotentin",
phone: "09 86 87 46 27",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_individuel_girault_philippe",
name: "GIRAULT Philippe",
family: "IDEL",
subType: "Individuel",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "25 rue Vauban, 50100 Cherbourg-en-Cotentin",
phone: "02 33 20 42 46",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "IDEL",
tags: ["IDEL", "Individuel", "Cherbourg", "en", "Cotentin"],
notes: "IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_laboulbene_lydie_laboulbene_gera",
name: "Cabinet LABOULBENE Lydie / LABOULBENE Géraldine / LEPOITTEVIN Renée / APPY Rémi",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "61 rue Roger-Salengro, 50100 Cherbourg-en-Cotentin",
phone: "02 33 94 88 82",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},
{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_leclerc_sophie_renard_emilie",
name: "Cabinet LECLERC Sophie / RENARD Émilie",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "8 rue des Fossés, 50100 Cherbourg-en-Cotentin",
phone: "02 33 93 45 12",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cherbourg"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_lemaitre_audrey_hardy_laura",
name: "Cabinet LEMAITRE Audrey / HARDY Laura",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "12 rue du Val de Saire, 50100 Cherbourg-en-Cotentin",
phone: "02 33 20 18 42",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cherbourg"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_individuel_leveque_marie",
name: "LEVEQUE Marie",
family: "IDEL",
subType: "Individuel",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "5 rue du Général Koenig, 50100 Cherbourg-en-Cotentin",
phone: "06 12 34 56 78",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "IDEL",
tags: ["IDEL", "Individuel", "Cherbourg"],
notes: "IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_pharmacie_cotentin_centre",
label: "Pharmacie du Centre",
type: "Pharmacie",
territory: ["Cotentin"],
categories: ["médicament"],
keywords: ["pharmacie"],
contact: {
phone: "02 33 44 55 66",
email: ""
},
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_laboratoire_cotentin",
label: "Laboratoire Cotentin",
type: "Laboratoire",
territory: ["Cotentin"],
categories: ["biologie"],
keywords: ["analyse", "laboratoire"],
contact: {
phone: "",
email: ""
},
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_transport_sanitaire",
label: "Transport sanitaire Cotentin",
type: "Transport",
territory: ["Cotentin"],
categories: ["transport"],
keywords: ["ambulance", "transport patient"],
contact: {
phone: "",
email: ""
},
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_psy_libéral",
label: "Psychologue libéral Cotentin",
type: "Psychologue",
territory: ["Cotentin"],
categories: ["santé mentale"],
keywords: ["psy", "psychologue"],
contact: {
phone: "",
email: ""
},
platform: null,
note: "",
source: "annuaire"
},

{
id: "annuaire_kine_cotentin",
label: "Kinésithérapeute Cotentin",
type: "Kiné",
territory: ["Cotentin"],
categories: ["rééducation"],
keywords: ["kiné"],
contact: {
phone: "",
email: ""
},
platform: null,
note: "",
source: "annuaire"
},
{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_le_heno_dominique_philip_dominiq",
name: "Cabinet LE HÉNO Dominique / PHILIP Dominique",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "109 rue Roger-Salengro, 50100 Cherbourg-en-Cotentin",
phone: "02 33 53 32 13",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_lemoine_stephanie_marie_sandri",
name: "Cabinet LEMOINE Stéphanie / MARIE Sandrine",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "24 rue des Claires, 50100 Cherbourg-en-Cotentin",
phone: "02 33 44 04 59",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_letellier_elodie_martin_anne_la",
name: "Cabinet LETELLIER Élodie / MARTIN Anne-Laure",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "16 rue Christine, 50100 Cherbourg-en-Cotentin",
phone: "02 33 44 63 13",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_mauduit_laetitia_roulleaux_j",
name: "Cabinet MAUDUIT Laetitia / ROULLEAUX Justine",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "8 rue de Bassigny, 50100 Cherbourg-en-Cotentin",
phone: "02 33 43 01 54",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_montier_viviane_montier_cle",
name: "Cabinet MONTIER Viviane / MONTIER Clémence",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "11 rue de l’Abbaye, 50100 Cherbourg-en-Cotentin",
phone: "02 33 20 19 94",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_nouet_virginie_simon_dorothee",
name: "Cabinet NOUET Virginie / SIMON Dorothée",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "2 rue Lucet, 50100 Cherbourg-en-Cotentin",
phone: "02 33 20 56 12",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_potel_sophie_rioult_aurelie",
name: "Cabinet POTEL Sophie / RIOULT Aurélie",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "46 rue de la Polle, 50100 Cherbourg-en-Cotentin",
phone: "02 33 53 52 11",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},
{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_renouf_sabrina_roux_virginie",
name: "Cabinet RENOUF Sabrina / ROUX Virginie",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "3 rue du Port, 50100 Cherbourg-en-Cotentin",
phone: "02 33 93 22 41",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_salmon_emilie_tison_anais",
name: "Cabinet SALMON Émilie / TISON Anaïs",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "27 avenue de Paris, 50100 Cherbourg-en-Cotentin",
phone: "02 33 44 18 73",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_schmidt_celine_thomas_sonia",
name: "Cabinet SCHMIDT Céline / THOMAS Sonia",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "9 rue Grande Vallée, 50100 Cherbourg-en-Cotentin",
phone: "02 33 20 11 27",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_cherbourg_en_cotentin_cabinet_cabinet_vernay_elodie_jeanne_sarah",
name: "Cabinet VERNAY Élodie / JEANNE Sarah",
family: "IDEL",
subType: "Cabinet",
territory: "Cherbourg-en-Cotentin",
zone: "Commune",
contactPerson: "",
address: "18 rue de l’Abbaye, 50100 Cherbourg-en-Cotentin",
phone: "02 33 53 90 14",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
sourceUrl: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Cabinet IDEL",
tags: ["IDEL", "Cabinet", "Cabinet IDEL", "Cherbourg", "en", "Cotentin"],
notes: "Cabinet IDEL",
recommended: false,
source: "annuaire",
platform: {
url: "https://www.norm-uni.fr/portail.pro/minisite_83/annuaire/professionnels-de-sante-du-cotentin/infirmiers-cherbourg-octeville-1-2-3%2C5210%2C11331.html",
},
},

{
id: "annuaire_valognes_ssiad_ssiad_valognes",
name: "SSIAD Valognes",
family: "SSIAD",
subType: "Service",
territory: "Valognes",
zone: "Commune",
contactPerson: "",
address: "",
phone: "",
email: "",
bestTimeToCall: "",
activationMode: "",
formLink: "",
sourceUrl: "",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "SSIAD",
tags: ["SSIAD", "Valognes", "domicile", "soins"],
notes: "Service de soins infirmiers à domicile",
recommended: false,
source: "annuaire",
platform: null,
},

{
id: "annuaire_valognes_ehpad_ehpad_valognes",
name: "EHPAD Valognes",
family: "EHPAD",
subType: "Établissement",
territory: "Valognes",
zone: "Commune",
contactPerson: "",
address: "",
phone: "",
email: "",
bestTimeToCall: "",
activationMode: "",
formLink: "",
sourceUrl: "",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "EHPAD",
tags: ["EHPAD", "Valognes", "hébergement"],
notes: "Établissement d’hébergement",
recommended: false,
source: "annuaire",
platform: null,
},

{
id: "annuaire_valognes_had_had_valognes",
name: "HAD Valognes",
family: "HAD",
subType: "Service",
territory: "Valognes",
zone: "Commune",
contactPerson: "",
address: "",
phone: "",
email: "",
bestTimeToCall: "",
activationMode: "",
formLink: "",
sourceUrl: "",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "HAD",
tags: ["HAD", "Valognes", "domicile"],
notes: "Hospitalisation à domicile",
recommended: false,
source: "annuaire",
platform: null,
},
{
id: "annuaire_valognes_clinique_clinique_valognes",
name: "Clinique Valognes",
family: "Clinique",
subType: "Établissement",
territory: "Valognes",
zone: "Commune",
contactPerson: "",
address: "",
phone: "",
email: "",
bestTimeToCall: "",
activationMode: "",
formLink: "",
sourceUrl: "",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Clinique",
tags: ["Clinique", "Valognes"],
notes: "",
recommended: false,
source: "annuaire",
platform: null,
},

{
id: "annuaire_cotentin_dac",
name: "DAC Cotentin",
family: "Coordination",
subType: "DAC",
territory: "Cotentin",
zone: "Territoire",
contactPerson: "",
address: "",
phone: "",
email: "",
bestTimeToCall: "",
activationMode: "lien",
formLink: "https://www.normandie-dac.fr",
sourceUrl: "https://www.normandie-dac.fr",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Coordination parcours",
tags: ["DAC", "coordination", "parcours"],
notes: "",
recommended: true,
source: "annuaire",
platform: {
url: "https://www.normandie-dac.fr",
},
},

{
id: "annuaire_cotentin_emsp",
name: "EMSP Cotentin",
family: "Equipe mobile",
subType: "Palliatif",
territory: "Cotentin",
zone: "Territoire",
contactPerson: "",
address: "",
phone: "",
email: "",
bestTimeToCall: "",
activationMode: "",
formLink: "",
sourceUrl: "",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Soins palliatifs",
tags: ["EMSP", "palliatif"],
notes: "",
recommended: true,
source: "annuaire",
platform: null,
},

{
id: "annuaire_cotentin_spasad",
name: "SPASAD Cotentin",
family: "Aide à domicile",
subType: "SPASAD",
territory: "Cotentin",
zone: "Territoire",
contactPerson: "",
address: "",
phone: "",
email: "",
bestTimeToCall: "",
activationMode: "",
formLink: "",
sourceUrl: "",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Aide et soins domicile",
tags: ["SPASAD", "domicile"],
notes: "",
recommended: false,
source: "annuaire",
platform: null,
},

{
id: "annuaire_cotentin_telealarme",
name: "Téléalarme Cotentin",
family: "Service",
subType: "Sécurité",
territory: "Cotentin",
zone: "Territoire",
contactPerson: "",
address: "",
phone: "",
email: "",
bestTimeToCall: "",
activationMode: "",
formLink: "",
sourceUrl: "",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Sécurité domicile",
tags: ["téléalarme", "chute"],
notes: "",
recommended: false,
source: "annuaire",
platform: null,
},

{
id: "annuaire_cotentin_portage_repas",
name: "Portage de repas Cotentin",
family: "Service",
subType: "Repas",
territory: "Cotentin",
zone: "Territoire",
contactPerson: "",
address: "",
phone: "",
email: "",
bestTimeToCall: "",
activationMode: "",
formLink: "",
sourceUrl: "",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Livraison repas",
tags: ["repas", "domicile"],
notes: "",
recommended: false,
source: "annuaire",
platform: null,
},

{
id: "annuaire_cotentin_transport",
name: "Transport sanitaire Cotentin",
family: "Transport",
subType: "Sanitaire",
territory: "Cotentin",
zone: "Territoire",
contactPerson: "",
address: "",
phone: "",
email: "",
bestTimeToCall: "",
activationMode: "",
formLink: "",
sourceUrl: "",
formDescription: "",
delay: "",
availableSlots: 0,
saturation: "unknown",
conditions: "Transport patient",
tags: ["ambulance", "transport"],
notes: "",
recommended: false,
source: "annuaire",
platform: null,
}

];