const FORM_PATHS = {
  had: "/forms/demande-had",
  hdj: "/forms/demande-hdj",
  ssiad: "/forms/demande-ssiad",
  aide: "/forms/evaluation-aide-domicile",
  social: "/forms/evaluation-sociale",
  juridique: "/forms/coordination-juridique",
  ase: "/forms/coordination-ase",
  autonomie: "/forms/demande-autonomie",
  habitat: "/forms/evaluation-habitat",
  psych: "/forms/orientation-psy",
  idel: "/forms/liaison-idel",
  pedia: "/forms/coordination-pediatrique",
};

function makeResource(resource) {
  const domain = resource.domain || "Coordination";
  const channels = resource.contactChannels || ["telephone", "email"];
  const forms = resource.forms || [];
  const services = resource.services || [];
  const publics = resource.publics || ["tout public"];
  const territoryTags = resource.territoryTags || [resource.commune].filter(Boolean);

  return {
    categories: [domain, ...(resource.categories || [])],
    keywords: [
      resource.type,
      domain,
      ...(resource.keywords || []),
      ...territoryTags,
      ...services,
      ...publics,
      ...forms.map((item) => item.label),
    ].filter(Boolean),
    verificationStatus: "base_realiste_a_verifier",
    sourceLabel: "Base ressources Carabbas",
    ...resource,
    domain,
    territoryTags,
    contactChannels: channels,
    forms,
    services,
    publics,
  };
}

export const resourceKnowledgeBase = [
  makeResource({
    id: "idel_cherbourg_dupont",
    label: "Cabinet infirmier Dupont",
    type: "IDEL",
    domain: "Soins",
    commune: "Cherbourg-en-Cotentin",
    adresse: "Centre-ville Cherbourg",
    phone: "02 33 20 45 67",
    email: "cabinet.dupont@idel-cotentin.fr",
    contactName: "Cabinet Dupont",
    coverage: "Cherbourg centre, Octeville, Tourlaville",
    activationMode: "appel direct ou fiche de liaison IDEL",
    delay: "24-48 h",
    territoryTags: ["Cherbourg", "Octeville", "Tourlaville"],
    services: ["pansements", "injections", "surveillance", "prise de sang"],
    forms: [{ label: "Fiche de liaison IDEL", url: FORM_PATHS.idel }],
    documents: ["ordonnance", "transmissions de sortie", "coordonnées patient"],
    publics: ["adulte", "personne âgée"],
    categories: ["Soins", "Domicile"],
    note: "Intervention rapide sur le secteur nord de Cherbourg.",
    keywords: ["pansement complexe", "sortie domicile", "surveillance rapprochée", "ide liberale"],
  }),
  makeResource({
    id: "idel_valognes_martin",
    label: "Cabinet Martin & associés",
    type: "IDEL",
    domain: "Soins",
    commune: "Valognes",
    adresse: "Valognes / Montebourg",
    phone: "02 33 40 12 98",
    email: "contact@martin-idel.fr",
    contactName: "Cabinet Martin",
    coverage: "Valognes, Montebourg, Brix",
    activationMode: "appel direct ou fiche de liaison IDEL",
    delay: "48 h",
    territoryTags: ["Valognes", "Montebourg", "Brix"],
    services: ["perfusion", "pansements", "surveillance chronique", "post-opératoire"],
    forms: [{ label: "Fiche de liaison IDEL", url: FORM_PATHS.idel }],
    documents: ["ordonnance", "compte rendu", "prescription infirmière"],
    publics: ["adulte", "retour postopératoire"],
    categories: ["Soins", "Domicile"],
    note: "Habitué des relais de sortie complexes sur le nord-est Cotentin.",
    keywords: ["perfusion", "sortie chirurgicale", "retour domicile"],
  }),
  makeResource({
    id: "ssiad_cotentin_nord",
    label: "SSIAD du Cotentin",
    type: "SSIAD",
    domain: "Soins",
    commune: "Cherbourg-en-Cotentin",
    adresse: "Cherbourg / Val de Saire",
    phone: "02 33 53 69 57",
    email: "coordination@ssiad-cotentin.fr",
    contactName: "Cadre SSIAD",
    coverage: "Nord Cotentin",
    activationMode: "demande SSIAD + évaluation infirmière",
    delay: "3 à 5 jours",
    territoryTags: ["Nord Cotentin", "Cherbourg", "Val de Saire"],
    services: ["soins à domicile", "toilette thérapeutique", "surveillance dépendance"],
    forms: [{ label: "Demande SSIAD", url: FORM_PATHS.ssiad }],
    documents: ["prescription", "évaluation autonomie", "coordonnées entourage"],
    publics: ["personne âgée", "retour fragile"],
    categories: ["Soins", "Autonomie"],
    note: "Fortement sollicité, à anticiper si la sortie est proche.",
    keywords: ["autonomie", "toilette", "dépendance", "soins domicile"],
  }),
  makeResource({
    id: "had_chpc_cotentin",
    label: "HAD Cotentin / CHPC",
    type: "HAD",
    domain: "Soins",
    commune: "Cherbourg-en-Cotentin",
    adresse: "Coordination HAD CHPC",
    phone: "02 33 20 70 00",
    email: "admission@had-cotentin.fr",
    contactName: "Coordination HAD",
    coverage: "Nord et centre Manche",
    activationMode: "prescription médicale + accord HAD",
    delay: "24 à 72 h",
    territoryTags: ["Nord Manche", "Centre Manche"],
    services: ["perfusion", "soins palliatifs", "soins complexes", "surveillance clinique"],
    forms: [{ label: "Demande HAD", url: FORM_PATHS.had }],
    documents: ["prescription médicale", "plan de soins", "coordonnées entourage"],
    publics: ["adulte", "personne âgée", "soins lourds"],
    categories: ["Soins", "Retour complexe"],
    note: "À mobiliser quand le domicile est possible mais nécessite un niveau de soins élevé.",
    keywords: ["soins lourds", "domicile sécurisé", "fin de vie", "perfusion"],
  }),
  makeResource({
    id: "hdj_coordination_chpc",
    label: "HDJ coordination et sortie sécurisée",
    type: "HDJ",
    domain: "Soins",
    commune: "Cherbourg-en-Cotentin",
    adresse: "CHPC - Pôle ambulatoire",
    phone: "02 33 88 60 12",
    email: "secretariat.hdj@ch-cotentin.fr",
    contactName: "Secrétariat HDJ",
    coverage: "Nord Cotentin",
    activationMode: "demande interne + validation médicale",
    delay: "24 à 72 h",
    territoryTags: ["Cherbourg", "ambulatoire", "sortie sécurisée"],
    services: ["réévaluation rapide", "coordination ville-hôpital", "surveillance", "éducation thérapeutique"],
    forms: [{ label: "Demande HDJ", url: FORM_PATHS.hdj }],
    documents: ["prescription", "objectif du HDJ", "date souhaitée de début"],
    publics: ["adulte", "personne âgée fragile", "sortie complexe"],
    categories: ["HDJ", "Sortie"],
    note: "Solution pivot pour une sortie sécurisée quand le domicile reste possible mais fragile.",
    keywords: ["hdj", "surveillance", "coordination", "sortie sécurisée"],
  }),
  makeResource({
    id: "admr_manche_maintien",
    label: "ADMR Manche",
    type: "AIDE_DOMICILE",
    domain: "Aide à domicile",
    commune: "Saint-Lô",
    adresse: "Couverture départementale Manche",
    phone: "02 33 05 55 00",
    email: "contact@admr50.fr",
    contactName: "Plateforme ADMR",
    coverage: "Département Manche",
    activationMode: "évaluation + planification",
    delay: "5 à 7 jours",
    territoryTags: ["Manche", "maintien domicile"],
    services: ["aide toilette", "repas", "ménage", "accompagnement"],
    forms: [{ label: "Évaluation aide à domicile", url: FORM_PATHS.aide }],
    documents: ["grille AVQ", "horaire souhaité", "coordonnées aidants"],
    publics: ["personne âgée", "retour domicile", "fragilité"],
    categories: ["Autonomie", "Domicile"],
    note: "Réseau large, délai variable selon le secteur.",
    keywords: ["aide domicile", "toilette", "repas", "retour domicile"],
  }),
  makeResource({
    id: "una_cotentin_aide",
    label: "UNA / aide et présence Cotentin",
    type: "AIDE_DOMICILE",
    domain: "Aide à domicile",
    commune: "Cherbourg-en-Cotentin",
    adresse: "Nord Cotentin",
    phone: "02 33 44 21 10",
    email: "coordination@una-cotentin.fr",
    contactName: "Coordinatrice UNA",
    coverage: "Nord Cotentin",
    activationMode: "évaluation rapide par téléphone",
    delay: "48 h à 5 jours",
    territoryTags: ["Cherbourg", "Cotentin"],
    services: ["présence à domicile", "repas", "aide humaine", "retour de week-end"],
    forms: [{ label: "Évaluation aide à domicile", url: FORM_PATHS.aide }],
    documents: ["besoins", "horaires", "contact famille"],
    publics: ["adulte", "retour à domicile"],
    categories: ["Autonomie", "Domicile"],
    note: "Utile pour sécuriser les premières journées après sortie.",
    keywords: ["présence", "week-end", "aide humaine"],
  }),
  makeResource({
    id: "dac_manche_parcours",
    label: "DAC Manche - appui parcours complexes",
    type: "COORDINATION",
    domain: "Coordination",
    commune: "Saint-Lô",
    adresse: "Appui territorial départemental",
    phone: "02 33 06 11 20",
    email: "coordination@dac-manche.fr",
    contactName: "Référent DAC",
    coverage: "Département Manche",
    activationMode: "saisine directe service ou médecin",
    delay: "24 h pour prise de contact",
    territoryTags: ["Manche", "parcours complexes"],
    services: ["concertation pluridisciplinaire", "appui sorties bloquées", "coordination multi-acteurs"],
    forms: [{ label: "Saisine DAC", url: FORM_PATHS.social }],
    documents: ["synthèse situation", "blocages", "acteurs déjà mobilisés"],
    publics: ["tout public", "situation complexe"],
    categories: ["Coordination", "Crise"],
    note: "Partenaire à mobiliser quand le service n’arrive plus à avancer seul.",
    keywords: ["dac", "cellule de crise", "coordination complexe", "sortie bloquée"],
  }),
  makeResource({
    id: "service_social_hospitalier",
    label: "Service social hospitalier",
    type: "SOCIAL_HOSPITALIER",
    domain: "Social",
    commune: "Cherbourg-en-Cotentin",
    adresse: "Établissement",
    phone: "02 33 88 70 14",
    email: "service.social@carabbas-hopital.fr",
    contactName: "Assistante sociale référente",
    coverage: "Établissement",
    activationMode: "saisine interne",
    delay: "J0 à J2",
    territoryTags: ["intra-hospitalier", "droits", "sortie"],
    services: ["droits", "aides financières", "logement", "coordination partenaire"],
    forms: [{ label: "Demande d'appui social", url: FORM_PATHS.social }],
    documents: ["situation sociale", "ressources", "contact entourage"],
    publics: ["adulte", "mineur", "famille"],
    categories: ["Social", "Sortie"],
    note: "À mobiliser tôt dans le séjour si fragilité sociale ou logement inadapté.",
    keywords: ["droits", "aide sociale", "logement", "précarité"],
  }),
  makeResource({
    id: "ccas_cherbourg",
    label: "CCAS Cherbourg-en-Cotentin",
    type: "CCAS",
    domain: "Social",
    commune: "Cherbourg-en-Cotentin",
    adresse: "Cherbourg-en-Cotentin",
    phone: "02 33 87 87 00",
    email: "ccas@cherbourg.fr",
    contactName: "Accueil CCAS",
    coverage: "Cherbourg-en-Cotentin",
    activationMode: "appel ou mail + dossier simple",
    delay: "variable selon aide",
    territoryTags: ["Cherbourg", "aides locales"],
    services: ["aides financières", "domiciliation", "orientation sociale"],
    forms: [{ label: "Saisine sociale locale", url: FORM_PATHS.social }],
    documents: ["justificatifs ressources", "situation synthétique"],
    publics: ["tout public", "précarité"],
    categories: ["Social", "Droits"],
    note: "Relais de proximité pour aides ponctuelles et ancrage local.",
    keywords: ["ccas", "aide financière", "domiciliation", "proximité"],
  }),
  makeResource({
    id: "siao_manche",
    label: "SIAO Manche",
    type: "SIAO",
    domain: "Logement",
    commune: "Saint-Lô",
    adresse: "Couverture départementale",
    phone: "115",
    email: "siao50@social.gouv.fr",
    contactName: "Plateforme SIAO",
    coverage: "Département Manche",
    activationMode: "saisine ou appel 115",
    delay: "selon disponibilité",
    territoryTags: ["hébergement", "urgence", "Manche"],
    services: ["orientation hébergement", "mise à l’abri", "évaluation situation"],
    forms: [{ label: "Saisine SIAO", url: FORM_PATHS.social }],
    documents: ["situation sociale", "motif urgence", "coordonnées patient"],
    publics: ["adultes", "sans solution logement"],
    categories: ["Logement", "Urgence sociale"],
    note: "Point d’entrée pour hébergement d’urgence et situations sans solution.",
    keywords: ["hébergement urgence", "sans domicile", "logement inadapté", "115"],
  }),
  makeResource({
    id: "croix_rouge_cherbourg",
    label: "Croix-Rouge française - Cherbourg",
    type: "ASSOCIATION",
    domain: "Social",
    commune: "Cherbourg-en-Cotentin",
    adresse: "Cherbourg-en-Cotentin",
    phone: "02 33 43 12 10",
    email: "cherbourg@croix-rouge.fr",
    contactName: "Unité locale",
    coverage: "Cherbourg et alentours",
    activationMode: "appel ou mail",
    delay: "selon disponibilité",
    territoryTags: ["association", "urgence sociale"],
    services: ["aide alimentaire", "vestiaire", "orientation"],
    forms: [{ label: "Demande appui associatif", url: FORM_PATHS.social }],
    documents: ["besoin identifié", "coordonnées"],
    publics: ["précarité", "retour sans solution"],
    categories: ["Social", "Association"],
    note: "Peut compléter un dispositif social institutionnel.",
    keywords: ["association", "aide alimentaire", "urgence"],
  }),
  makeResource({
    id: "mda_autonomie_manche",
    label: "Maison départementale de l'autonomie",
    type: "AUTONOMIE",
    domain: "Autonomie",
    commune: "Saint-Lô",
    adresse: "Maison départementale de l'autonomie",
    phone: "02 33 55 10 00",
    email: "autonomie@manche.fr",
    contactName: "Accueil MDA",
    coverage: "Département Manche",
    activationMode: "dossier administratif",
    delay: "instruction selon dossier",
    territoryTags: ["autonomie", "handicap", "apa", "pch"],
    services: ["APA", "PCH", "orientation autonomie", "aides handicap"],
    forms: [{ label: "Demande autonomie", url: FORM_PATHS.autonomie }],
    documents: ["formulaire usager", "justificatifs", "évaluation situation"],
    publics: ["personne âgée", "handicap", "aidants"],
    categories: ["Autonomie", "Droits"],
    note: "Important si la sortie nécessite un montage autonomie à moyen terme.",
    keywords: ["apa", "pch", "autonomie", "handicap", "aidant"],
  }),
  makeResource({
    id: "plateforme_habitat_manche",
    label: "Plateforme habitat et adaptation du logement",
    type: "HABITAT",
    domain: "Logement",
    commune: "Coutances",
    adresse: "Coutances",
    phone: "02 33 19 12 40",
    email: "habitat@manche.fr",
    contactName: "Conseiller habitat",
    coverage: "Centre et nord Manche",
    activationMode: "orientation sociale / ergothérapie",
    delay: "5 à 10 jours",
    territoryTags: ["logement", "adaptation", "retour domicile"],
    services: ["évaluation logement", "adaptation salle de bain", "aides techniques"],
    forms: [{ label: "Évaluation habitat", url: FORM_PATHS.habitat }],
    documents: ["description du logement", "photos si possible", "motif du blocage"],
    publics: ["retour domicile", "prévention chutes"],
    categories: ["Logement", "Prévention"],
    note: "À mobiliser si le logement freine ou empêche la sortie.",
    keywords: ["escalier", "barre d'appui", "adaptation logement", "prévention chute"],
  }),
  makeResource({
    id: "cmp_adulte_nord_manche",
    label: "CMP adulte Nord Manche",
    type: "CMP",
    domain: "Psychiatrie",
    commune: "Cherbourg-en-Cotentin",
    adresse: "Centre médico-psychologique adulte",
    phone: "02 33 88 51 20",
    email: "cmp.adulte@epsm50.fr",
    contactName: "Secrétariat CMP adulte",
    coverage: "Nord Cotentin",
    activationMode: "orientation médicale ou coordination",
    delay: "selon triage",
    territoryTags: ["psy adulte", "souffrance psychique"],
    services: ["évaluation psychique", "relais ambulatoire", "avis de crise"],
    forms: [{ label: "Orientation psychiatrie adulte", url: FORM_PATHS.psych }],
    documents: ["synthèse situation", "motif orientation"],
    publics: ["adulte"],
    categories: ["Psychiatrie", "Ambulatoire"],
    note: "Relais utile si souffrance psychique ou vigilance particulière après hospitalisation.",
    keywords: ["psychique", "cmp", "ambulatoire", "crise"],
  }),
  makeResource({
    id: "pedopsy_cmpea_nord",
    label: "CMPEA / pédopsy Nord Manche",
    type: "PEDOPSY",
    domain: "Psychiatrie",
    commune: "Cherbourg-en-Cotentin",
    adresse: "Unité enfants-adolescents",
    phone: "02 33 88 51 45",
    email: "pedopsy@epsm50.fr",
    contactName: "Secrétariat pédopsy",
    coverage: "Nord Manche",
    activationMode: "orientation médicale / coordination enfant",
    delay: "selon évaluation initiale",
    territoryTags: ["enfant", "adolescent", "famille"],
    services: ["consultation pédopsy", "avis enfant", "coordination école-famille"],
    forms: [{ label: "Orientation pédopsy", url: FORM_PATHS.pedia }],
    documents: ["synthèse situation", "éléments famille", "observations du service"],
    publics: ["enfant", "adolescent"],
    categories: ["Pédiatrie", "Santé mentale"],
    note: "À activer si le besoin concerne l’enfant et non seulement l’hospitalisation.",
    keywords: ["enfance", "adolescent", "souffrance", "famille"],
  }),
  makeResource({
    id: "ase_manche_referent",
    label: "ASE Manche - coordination protection enfance",
    type: "ASE",
    domain: "Pédiatrie",
    commune: "Saint-Lô",
    adresse: "Conseil départemental de la Manche",
    phone: "02 33 55 70 00",
    email: "coordination.ase@manche.fr",
    contactName: "Référent ASE",
    coverage: "Département Manche",
    activationMode: "coordination conditionnelle selon critères protection enfance",
    delay: "selon niveau de vigilance",
    territoryTags: ["ASE", "protection enfance", "mineur"],
    services: ["coordination ASE", "préparation d'instance", "lien structures enfance"],
    forms: [{ label: "Lettre de liaison ASE", url: FORM_PATHS.ase }, { label: "Préparation d'instance ASE", url: FORM_PATHS.ase }],
    documents: ["synthèse situation", "motifs de vigilance", "coordonnées famille"],
    publics: ["mineur", "enfant", "famille"],
    categories: ["Pédiatrie", "Protection enfance"],
    note: "À activer uniquement si des critères de protection ou de besoin spécifique sont présents.",
    keywords: ["protection enfance", "mineur", "famille complexe", "ase"],
  }),
  makeResource({
    id: "pmi_cherbourg",
    label: "PMI Cherbourg",
    type: "PMI",
    domain: "Pédiatrie",
    commune: "Cherbourg-en-Cotentin",
    adresse: "PMI territoriale Cherbourg",
    phone: "02 33 54 12 30",
    email: "pmi.cherbourg@manche.fr",
    contactName: "Référente PMI",
    coverage: "Cherbourg et alentours",
    activationMode: "appel / coordination enfant",
    delay: "selon situation",
    territoryTags: ["PMI", "petite enfance", "famille"],
    services: ["suivi nourrisson", "lien domicile", "coordination famille"],
    forms: [{ label: "Coordination pédiatrique", url: FORM_PATHS.pedia }],
    documents: ["synthèse enfant", "date de sortie", "coordonnées famille"],
    publics: ["mineur", "nourrisson", "famille"],
    categories: ["Pédiatrie", "Prévention"],
    note: "Relais utile pour continuité du suivi d'un enfant après hospitalisation.",
    keywords: ["pmi", "enfant", "nourrisson", "famille"],
  }),
  makeResource({
    id: "juridique_protection_etablissement",
    label: "Référent juridique protection et consentement",
    type: "JURIDIQUE",
    domain: "Juridique",
    commune: "Cherbourg-en-Cotentin",
    adresse: "Établissement",
    phone: "02 33 88 61 30",
    email: "juridique.parcours@carabbas-hopital.fr",
    contactName: "Référent juridique",
    coverage: "Établissement et territoire",
    activationMode: "appui expert interne",
    delay: "J0 à J3 selon urgence",
    territoryTags: ["tutelle", "curatelle", "consentement"],
    services: ["tutelle", "curatelle", "consentement", "appui décisionnel"],
    forms: [{ label: "Demande d'appui juridique", url: FORM_PATHS.juridique }],
    documents: ["question posée", "synthèse situation", "mesure existante"],
    publics: ["adulte protégé", "mineur", "famille"],
    categories: ["Juridique", "Protection"],
    note: "À mobiliser quand la sortie est freinée par une mesure de protection ou un doute juridique.",
    keywords: ["tutelle", "curatelle", "protection", "mandataire"],
  }),
];
