export const officialForms50 = {
apa: {
id: "apa-50",
label: "APA - Demande d'aides à l'autonomie",
type: "official-form",
authority: "Département de la Manche",
officialUrl: "https://www.service-public.fr/particuliers/vosdroits/R64469",
note: "Cerfa 16301*01 - à orienter vers le circuit autonomie du Département",
territory: "50",
},
mdph: {
id: "mdph-50",
label: "MDPH - Formulaire de demande",
type: "official-form",
authority: "MDPH / MDA Manche",
officialUrl: "https://www.manche.fr/demarches/vivre-mon-handicap/suivre-mon-dossier-daides/",
note: "Formulaire Cerfa 15692*01 + certificat médical à joindre",
territory: "50",
},
mdphMedical: {
id: "mdph-medical-50",
label: "MDPH - Certificat médical",
type: "official-form",
authority: "MDPH / MDA Manche",
officialUrl: "https://www.manche.fr/demarches/vivre-mon-handicap/suivre-mon-dossier-daides/",
note: "Certificat médical à faire compléter par le médecin",
territory: "50",
},
ase: {
id: "ase-50",
label: "ASE / CRIP - Circuit départemental Manche",
type: "official-circuit",
authority: "Département de la Manche",
officialUrl: "https://www.manche.fr/demarches/etre-parent/signaler-un-enfant-en-danger/",
note: "Signalement via 119 et circuit départemental de recueil des informations préoccupantes",
territory: "50",
},
};

export const coordinationContacts50 = [
{
id: "had-cotentin",
type: "HAD",
name: "HAD Cotentin",
territory: "Cherbourg / Nord Manche",
phone: "02 33 00 00 01",
email: "contact.had.cotentin@example.fr",
note: "Soins complexes à domicile, coordination médicale et infirmière",
},
{
id: "ssiad-cotentin",
type: "SSIAD",
name: "SSIAD Cotentin",
territory: "Cherbourg / Valognes",
phone: "02 33 00 00 02",
email: "contact.ssiad.cotentin@example.fr",
note: "Dépendance, aide aux soins d'hygiène, surveillance",
},
{
id: "idel-reseau",
type: "IDEL",
name: "Réseau IDEL territorial",
territory: "Manche",
phone: "02 33 00 00 03",
email: "coordination.idel@example.fr",
note: "Pansements, injections, surveillance, suivi domicile",
},
{
id: "aide-domicile",
type: "Aide à domicile",
name: "Service aide à domicile Nord Manche",
territory: "Cherbourg / Equeurdreville / Valognes",
phone: "02 33 00 00 04",
email: "aide.domicile@example.fr",
note: "Aide humaine, repas, lever/coucher, entretien",
},
{
id: "dac",
type: "DAC",
name: "DAC Manche",
territory: "Manche",
phone: "02 33 00 00 05",
email: "dac.manche@example.fr",
note: "Coordination des parcours complexes",
},
{
id: "cpts",
type: "CPTS",
name: "CPTS du territoire",
territory: "Territoire de proximité",
phone: "02 33 00 00 06",
email: "contact.cpts@example.fr",
note: "Coordination ville-hôpital et relais de proximité",
},
{
id: "pmi",
type: "PMI",
name: "PMI Manche",
territory: "Manche",
phone: "02 33 00 00 07",
email: "pmi@example.fr",
note: "Suivi mère-enfant, parentalité, évaluation à domicile",
},
];

export const aseContacts50 = {
name: "Cellule ASE / CRIP - Manche",
phone: "02 33 05 55 50",
emergencyPhone: "119",
postalAddress:
"Monsieur le Président du conseil départemental de la Manche, Service de l’aide sociale à l’enfance, Cellule de recueil des informations préoccupantes, 50050 Saint-Lô Cedex",
};
