export const arsMockRequests = [
{
id: "REQ_001",
category: "Pédopsy",
patientLabel: "Ado crise suicidaire",

attempts: [],
arsEscalated: false,
patientAge: 15,
requesterHospital: "CH Mémorial Saint-Lô",
toHospitalName: "Fondation Bon Sauveur",
originService: "Urgences pédiatriques",
need: "HDJ pédopsy crise",
waitingHours: 32,
status: "Routé",
priority: "critical",
},
{
id: "REQ_002",
category: "Pédopsy",
patientLabel: "TSA rupture scolaire",
attempts: [],
arsEscalated: false,
patientAge: 12,
requesterHospital: "CH Public du Cotentin (CHPC)",
toHospitalName: "Fondation Bon Sauveur",
originService: "Pédiatrie",
need: "HDJ neurodéveloppement",
waitingHours: 18,
status: "Accepté",
priority: "normal",
},
{
id: "REQ_003",
category: "Gériatrie",
patientLabel: "Fragilité post-chute",
attempts: [],
arsEscalated: false,
patientAge: 84,
requesterHospital: "Hôpitaux Sud-Manche",
toHospitalName: "CH Mémorial Saint-Lô",
originService: "Médecine polyvalente",
need: "HDJ gériatrie autonomie",
waitingHours: 44,
status: "Refus capacité",
priority: "critical",
},
{
id: "REQ_004",
category: "Pédopsy",
patientLabel: "Ado anxiété majeure",
attempts: [],
arsEscalated: false,
patientAge: 16,
requesterHospital: "CH Coutances",
toHospitalName: "Fondation Bon Sauveur",
originService: "Urgences",
need: "HDJ pédopsy régulation",
waitingHours: 27,
status: "En évaluation",
priority: "critical",
},
{
id: "REQ_005",
category: "Gériatrie",
patientLabel: "Troubles mémoire",
attempts: [],
arsEscalated: false,
patientAge: 79,
requesterHospital: "CH Public du Cotentin (CHPC)",
toHospitalName: "CH Mémorial Saint-Lô",
originService: "Gériatrie",
need: "HDJ mémoire",
waitingHours: 12,
status: "Programmé",
priority: "normal",
},
{
id: "REQ_006",
category: "Social / ASE",
patientLabel: "Mineur sans relais",
attempts: [],
arsEscalated: false,
patientAge: 14,
requesterHospital: "Hôpitaux Sud-Manche",
toHospitalName: "Fondation Bon Sauveur",
originService: "Pédiatrie",
need: "Situation ASE / pédopsy sans relais",
waitingHours: 61,
status: "Sans solution",
priority: "critical",
},
{
id: "REQ_007",
category: "Gériatrie",
patientLabel: "Dénutrition fragile",
attempts: [],
arsEscalated: false,
patientAge: 87,
requesterHospital: "CH Carentan-les-Marais",
toHospitalName: "CH Mémorial Saint-Lô",
originService: "Médecine",
need: "HDJ gériatrie nutrition",
waitingHours: 9,
status: "Accepté",
priority: "normal",
},
{
id: "REQ_008",
category: "Retour domicile",
patientLabel: "Retour domicile impossible",
attempts: [],
arsEscalated: false,
patientAge: 81,
requesterHospital: "CH Saint-Hilaire-du-Harcouët",
toHospitalName: "Hôpitaux Sud-Manche",
originService: "Médecine polyvalente",
need: "Sortant médical sans solution domicile",
waitingHours: 38,
status: "En évaluation",
priority: "critical",
},
{
id: "REQ_009",
category: "HDJ",
patientLabel: "Soins techniques programmés",
attempts: [],
arsEscalated: false,
patientAge: 63,
requesterHospital: "Hôpital Privé de la Manche",
toHospitalName: "CH Public du Cotentin (CHPC)",
originService: "Chirurgie",
need: "HDJ actes techniques",
waitingHours: 7,
status: "Programmé",
priority: "normal",
},
{
id: "REQ_010",
category: "Pédopsy",
patientLabel: "Crise anxiodépressive",
attempts: [],
arsEscalated: false,
patientAge: 17,
requesterHospital: "EPSM Manche",
toHospitalName: "Fondation Bon Sauveur",
originService: "Santé mentale",
need: "HDJ pédopsy transition",
waitingHours: 25,
status: "Routé",
priority: "critical",
},
{
id: "REQ_011",
category: "SSR / SMR",
patientLabel: "Post-opératoire sans place SMR",
attempts: [],
arsEscalated: false,
patientAge: 72,
requesterHospital: "CH Mémorial Saint-Lô",
toHospitalName: "Hôpitaux Sud-Manche",
originService: "Chirurgie orthopédique",
need: "Recherche SMR après chirurgie",
waitingHours: 52,
status: "Sans solution",
priority: "critical",
},
{
id: "REQ_012",
category: "HAD",
patientLabel: "Soins complexes à domicile",
attempts: [],
arsEscalated: false,
patientAge: 68,
requesterHospital: "CH Public du Cotentin (CHPC)",
toHospitalName: "HAD Manche",
originService: "Médecine",
need: "HAD pansements complexes",
waitingHours: 16,
status: "En évaluation",
priority: "normal",
},
{
id: "REQ_013",
category: "EHPAD / USLD",
patientLabel: "Grand âge sans solution aval",
attempts: [],
arsEscalated: false,
patientAge: 91,
requesterHospital: "CH Coutances",
toHospitalName: "EHPAD territoire Centre-Manche",
originService: "Gériatrie",
need: "Recherche place EHPAD urgente",
waitingHours: 74,
status: "Sans solution",
priority: "critical",
},
{
id: "REQ_014",
category: "Soins palliatifs",
patientLabel: "Fin de vie sans solution adaptée",
attempts: [],
arsEscalated: false,
patientAge: 76,
requesterHospital: "Hôpitaux Sud-Manche",
toHospitalName: "USP / équipe mobile territoriale",
originService: "Oncologie",
need: "Orientation soins palliatifs",
waitingHours: 29,
status: "Routé",
priority: "critical",
},
];
