export const subcategoryCatalog = {
Adultes: {
"Soins lourds": [
"Nursing lourd",
"Surveillance rapprochée",
"Prévention d’escarres",
"Pansements complexes",
"Perfusions",
"Oxygénothérapie",
"Perte d'autonomie sévères",
],
"Aides à domicile": [
"Aide à la toilette",
"Aide au lever",
"Aide au coucher",
"Aide aux repas",
"Aide ménagère",
"Téléassistance",
"Passage infirmier quotidien",
"Ergothérapie",
],
"Solutions d’aval": [
"Retour à domicile avec aides",
"HAD adulte",
"SSIAD",
"SPASAD",
"EHPAD",
"Hébergement temporaire",
"Accueil de jour",
"Transport sanitaire",
"HDJ cardiologie",
],
Social: [
"Isolement social",
"Précarité",
"Logement inadapté",
"Absence d’aidants",
"Aidant épuisé",
"Ouverture de droits",
"Difficultés financières",
"Accès aux soins difficile",
"Protection juridique",
],
},

Pédiatrie: {
Soins: [
"Nursing pédiatrique",
"Soins techniques pédiatriques",
"Surveillance rapprochée enfant",
"Oxygénothérapie pédiatrique",
"Enfant dépendant",
"Sonde nasogastrique",
],
Aides: [
"Soutien parental",
"Aide éducative",
"Répit parental",
"Coordination PMI",
],
"Solutions d’aval": [
"Retour à domicile accompagné",
"HAD pédiatrique",
"IDEL pédiatrique",
"CAMSP",
"SESSAD",
"Transport pédiatrique",
],
Social: [
"Situation familiale complexe",
"Famille isolée",
"Précarité familiale",
"Absence de relais parental",
"Logement précaire",
"Protection de l’enfance",
],
},

Maternité: {
Soins: [
"Nursing post-partum",
"Surveillance post-césarienne",
"Allaitement accompagné",
"Fatigue maternelle importante",
],
Aides: [
"Aide à domicile jeune mère",
"Soutien parental",
"Aide aux soins du nouveau-né",
"Aide aux repas",
],
"Solutions d’aval": [
"Retour à domicile avec sage-femme",
"HAD post-partum",
"Suivi PMI",
"Aide à domicile parentale",
"Transport mère-enfant",
],
Social: [
"Vulnérabilité maternelle",
"Précarité périnatale",
"Absence de réseau familial",
"Suivi PMI nécessaire",
"Hébergement d’urgence famille",
"Violence conjugale",
],
},
};