export const CopiloteCategories = [
{
key: "domicile",
label: "Retour domicile",
items: [
"Retour à domicile avec aides",
"Aide à la toilette",
"Aide au lever",
"Aide au coucher",
"Aide aux repas",
"Aide ménagère",
"Téléassistance",
"Transport sanitaire",
"Logement inadapté",
"Absence d’aidants",
"Isolement social",
"Précarité",
"Ouverture de droits",
],
},
{
key: "soins",
label: "Soins techniques",
items: [
"Pansements complexes",
"Perfusions",
"Passage infirmier quotidien",
"Nursing lourd",
"Surveillance rapprochée",
"IDEL",
"HAD adulte",
"SSIAD",
],
},
{
key: "hdj",
label: "HDJ / rééducation",
items: [
"HDJ",
"Rééducation",
"Suivi pluridisciplinaire",
"Bilan spécialisé",
"Kiné",
"Ergo",
"Orthophonie",
"Psychologue",
"Douleur",
"Oncologie",
"Cardio",
"Gériatrie",
],
},
{
key: "social",
label: "Social / administratif",
items: [
"Ouverture de droits",
"MDPH",
"APA",
"Précarité",
"Isolement social",
"Absence d’aidants",
"DAC",
"CPTS",
"Aide à domicile",
],
},
{
key: "pediatrie",
label: "Pédiatrie / ASE",
items: [
"Soutien parental",
"Absence de relais parental",
"Situation familiale complexe",
"Famille isolée",
"Précarité familiale",
"Protection de l’enfance",
"ASE",
"HAD pédiatrique",
"IDEL pédiatrique",
],
},
{
key: "maternite",
label: "Maternité / post-partum",
items: [
"Soutien parental",
"Suivi PMI",
"Suivi PMI nécessaire",
"HAD post-partum",
"Aide à domicile jeune mère",
"Sage-femme",
"Fatigue maternelle",
"Isolement post-partum",
],
},
];