export const AVAILABLE_FORMS = [
{
id: "form_signalement_social",
label: "Signalement social",
type: "coordination",
url: "https://exemple.fr/signalement-social",
category: "Social",
subcategories: [
"Isolement",
"Absence aidant",
"Précarité",
"Besoin accompagnement social",
],
recipient: "Service social",
usage: "Initier un accompagnement social structuré",
requiredDocuments: ["Résumé situation", "Coordonnées patient", "Freins identifiés"],
linkedResourceId: "service_social_cotentin",
},
{
id: "form_aide_domicile",
label: "Demande aide à domicile",
type: "coordination",
url: "https://exemple.fr/aide-domicile",
category: "Social",
subcategories: [
"Isolement",
"Absence aidant",
"Logement inadapté",
"Besoin accompagnement social",
],
recipient: "Service aide à domicile",
usage: "Solliciter une aide humaine au domicile",
requiredDocuments: ["Coordonnées patient", "Adresse", "Besoins"],
linkedResourceId: "aide_domicile_cotentin",
},
{
id: "form_nettoyage_logement",
label: "Demande nettoyage logement",
type: "coordination",
url: "https://exemple.fr/nettoyage-logement",
category: "Social",
subcategories: ["Logement inadapté", "Précarité"],
recipient: "Prestataire logement / coordination sociale",
usage: "Remise en état du logement avant retour",
requiredDocuments: ["Adresse", "Résumé situation", "Évaluation besoin"],
linkedResourceId: "nettoyage_logement_cotentin",
},
{
id: "form_portage_repas",
label: "Demande portage repas",
type: "coordination",
url: "https://exemple.fr/portage-repas",
category: "Social",
subcategories: ["Isolement", "Absence aidant", "Perte d’autonomie"],
recipient: "Service portage repas",
usage: "Sécuriser l’alimentation au domicile",
requiredDocuments: ["Adresse", "Coordonnées patient"],
linkedResourceId: "portage_repas_cotentin",
},
{
id: "form_teleassistance",
label: "Demande téléassistance",
type: "coordination",
url: "https://exemple.fr/teleassistance",
category: "Autonomie / Gérontologie",
subcategories: ["Perte d’autonomie", "Chute", "Isolement"],
recipient: "Opérateur téléassistance",
usage: "Sécuriser un retour domicile à risque",
requiredDocuments: ["Coordonnées patient", "Adresse"],
linkedResourceId: "teleassistance_cotentin",
},
{
id: "form_ergo_domicile",
label: "Demande évaluation ergo domicile",
type: "coordination",
url: "https://exemple.fr/ergo-domicile",
category: "Autonomie / Gérontologie",
subcategories: ["Logement inadapté", "Perte d’autonomie", "Chute"],
recipient: "Ergothérapie domicile",
usage: "Évaluer le domicile avant retour",
requiredDocuments: ["Adresse", "Résumé situation"],
linkedResourceId: "ergotherapie_domicile_cotentin",
},
{
id: "form_hebergement_temporaire",
label: "Demande hébergement temporaire",
type: "orientation",
url: "https://exemple.fr/hebergement-temporaire",
category: "Social",
subcategories: ["Logement inadapté", "Précarité", "Rupture entourage", "Absence aidant"],
recipient: "Structure hébergement temporaire",
usage: "Retour domicile impossible temporairement",
requiredDocuments: ["Résumé situation", "Coordonnées patient", "Adresse"],
linkedResourceId: "hebergement_temporaire_cotentin",
},
{
id: "form_usp_chpc_valognes",
label: "Dossier de pré-admission USP",
type: "orientation",
url: "https://extranet.ch-cotentin.fr/preadusp/",
category: "Coordination de soins",
subcategories: ["Organisation complexe", "Multiplicité intervenants"],
recipient: "USP CHPC Valognes",
usage: "Pré-admission en unité de soins palliatifs",
requiredDocuments: [
"Coordonnées patient et entourage",
"Données sociales",
"Volet médical",
"Autonomie et charges en soins",
"Objectifs du séjour",
"Transmissions du jour",
],
linkedResourceId: "usp_chpc_valognes",
},
{
id: "form_had_standard",
label: "Demande HAD",
type: "orientation",
url: "https://exemple.fr/demande-had",
category: "Coordination de soins",
subcategories: ["Besoin HAD", "Soins techniques à organiser"],
recipient: "Coordination HAD",
usage: "Relais HAD",
requiredDocuments: ["Synthèse médicale", "Coordonnées patient"],
linkedResourceId: "had_nord",
},
{
id: "form_hdj_standard",
label: "Demande HDJ",
type: "orientation",
url: "https://exemple.fr/demande-hdj",
category: "Coordination de soins",
subcategories: ["Organisation complexe", "Soins techniques à organiser", "Absence IDE"],
recipient: "Secrétariat HDJ",
usage: "Construire et programmer un HDJ de parcours",
requiredDocuments: ["Actes demandés", "Date souhaitée", "Récurrence"],
linkedResourceId: "hdj_polyvalent",
},
{
id: "form_smr_standard",
label: "Demande SMR / SSR via Trajectoire",
type: "orientation",
url: "https://trajectoire.sante-ra.fr",
category: "Coordination de soins",
subcategories: ["Besoin SMR"],
recipient: "Filière SMR / SSR",
usage: "Créer et suivre une demande SMR / SSR",
requiredDocuments: ["Résumé situation", "Éléments de prise en charge"],
linkedResourceId: "smr_via_trajectoire",
},
{
id: "form_ssiad_standard",
label: "Demande SSIAD",
type: "orientation",
url: "https://exemple.fr/demande-ssiad",
category: "Coordination de soins",
subcategories: ["Absence IDE", "Perte d’autonomie", "Besoin aidant"],
recipient: "SSIAD",
usage: "Relais SSIAD au domicile",
requiredDocuments: ["Coordonnées patient", "Évaluation besoin"],
linkedResourceId: "ssiad_est",
},
{
id: "form_coordination_domicile",
label: "Coordination domicile",
type: "coordination",
url: "https://exemple.fr/coordination-domicile",
category: "Coordination de soins",
subcategories: ["Absence IDE", "Coordination ville-hôpital", "Soins techniques à organiser"],
recipient: "Coordination domicile",
usage: "Structurer un retour domicile avec relais",
requiredDocuments: ["Coordonnées patient", "Besoins de relais"],
linkedResourceId: "ide_liberal_cotentin",
},
{
id: "form_trajectoire",
label: "Trajectoire EHPAD",
type: "orientation",
url: "https://trajectoire.sante-ra.fr",
category: "Autonomie / Gérontologie",
subcategories: ["Besoin EHPAD", "Dépendance lourde", "Épuisement entourage"],
recipient: "Plateforme Trajectoire",
usage: "Créer et suivre une demande EHPAD",
requiredDocuments: ["Dossier patient", "Évaluation autonomie"],
linkedResourceId: "ehpad_via_trajectoire",
},
{
id: "form_ehpad_temporaire",
label: "Demande EHPAD temporaire",
type: "orientation",
url: "https://exemple.fr/demande-ehpad-temporaire",
category: "Autonomie / Gérontologie",
subcategories: ["Besoin EHPAD", "Épuisement entourage"],
recipient: "Admissions EHPAD temporaire",
usage: "Solution temporaire / répit",
requiredDocuments: ["Évaluation autonomie", "Coordonnées entourage"],
linkedResourceId: "ehpad_temp_cotentin",
},
{
id: "form_ehpad_prive",
label: "Dossier EHPAD privé",
type: "orientation",
url: "https://exemple.fr/dossier-ehpad-prive",
category: "Autonomie / Gérontologie",
subcategories: ["Besoin EHPAD", "Dépendance lourde", "Épuisement entourage"],
recipient: "Admissions EHPAD privés",
usage: "Admission directe en EHPAD privé",
requiredDocuments: ["Dossier patient", "Évaluation autonomie"],
linkedResourceId: "ehpad_prives_cotentin",
},
{
id: "form_pmi_standard",
label: "Lien PMI",
type: "coordination",
url: "https://exemple.fr/pmi",
category: "Pédiatrie / Maternité",
subcategories: ["PMI", "Retour renforcé", "Accompagnement parental"],
recipient: "PMI",
usage: "Organiser un relais PMI",
requiredDocuments: ["Coordonnées famille", "Résumé situation"],
linkedResourceId: "pmi_cotentin",
},
{
id: "form_ase_standard",
label: "Lien ASE",
type: "coordination",
url: "https://exemple.fr/ase",
category: "Pédiatrie / Maternité",
subcategories: ["ASE", "Signalement", "Placement"],
recipient: "ASE",
usage: "Protection de l’enfance",
requiredDocuments: ["Signalement", "Résumé de situation"],
linkedResourceId: "ase_cotentin",
},
{
id: "form_pedopsy_standard",
label: "Demande pédopsy",
type: "orientation",
url: "https://exemple.fr/pedopsy",
category: "Pédiatrie / Maternité",
subcategories: ["Structure pédopsy", "CMP / CMPP", "HDJ pédopsy"],
recipient: "Pédopsy",
usage: "Orientation pédopsy spécialisée",
requiredDocuments: ["Résumé clinique", "Coordonnées entourage"],
linkedResourceId: "pedopsy_cotentin",
},
{
id: "form_reseau_perinatalite",
label: "Lien réseau périnatalité",
type: "coordination",
url: "https://exemple.fr/reseau-perinatalite",
category: "Pédiatrie / Maternité",
subcategories: ["Réseau périnatalité", "Maternité vulnérable", "Sortie mère-enfant fragile"],
recipient: "Réseau périnatalité",
usage: "Relais périnatalité",
requiredDocuments: ["Résumé situation", "Coordonnées mère / enfant"],
linkedResourceId: "reseau_perinatalite",
},
];