export const TERRITORY_HOSPITALS_MANCHE = [
{
id: "ch_cotentin",
name: "Centre Hospitalier Public du Cotentin",
city: "Cherbourg-en-Cotentin",
territory: "Nord Cotentin",
type: "CH",
phone: "02 33 20 70 00",
email: "secretariat.hdj@ch-cotentin.fr",
hdj: [
{ type: "gériatrie", tags: ["gériatrie", "fragilité", "autonomie", "chute"], pathways: ["hdj_geriatrie", "hdj_fragilite"] },
{ type: "mémoire", tags: ["mémoire", "cognition", "alzheimer", "désorientation"], pathways: ["hdj_memoire"] },
{ type: "médecine polyvalente", tags: ["ferinject", "transfusion", "perfusion", "ponction ascite", "pansement"], pathways: ["hdj_ferinject", "hdj_transfusion", "hdj_ascite", "hdj_pansements"] },
],
},
{
id: "ch_saint_lo",
name: "CH Mémorial France - États-Unis",
city: "Saint-Lô",
territory: "Centre Manche",
type: "CH",
phone: "02 33 06 33 33",
email: "secretariat.hdj@ch-stlo.fr",
hdj: [
{ type: "gériatrie", tags: ["gériatrie", "fragilité", "autonomie"], pathways: ["hdj_geriatrie", "hdj_fragilite"] },
{ type: "oncologie / soins support", tags: ["oncologie", "cancer", "douleur", "nutrition", "fatigue"], pathways: ["hdj_soins_support", "hdj_douleur", "hdj_nutrition"] },
{ type: "médecine polyvalente", tags: ["médecine", "traitement", "perfusion", "transfusion", "post hospitalisation"], pathways: ["hdj_ferinject", "hdj_transfusion", "hdj_therapeutique"] },
],
},
{
id: "ch_avranches_granville",
name: "CH Avranches-Granville",
city: "Avranches / Granville",
territory: "Sud Manche",
type: "CH",
phone: "02 33 89 40 00",
email: "secretariat.hdj@ch-avranches-granville.fr",
hdj: [
{ type: "gériatrie", tags: ["gériatrie", "autonomie", "fragilité", "retour domicile"], pathways: ["hdj_geriatrie", "hdj_fragilite"] },
{ type: "médecine ambulatoire", tags: ["ambulatoire", "perfusion", "transfusion", "réévaluation"], pathways: ["hdj_ferinject", "hdj_transfusion", "hdj_post_hospit"] },
{ type: "soins support", tags: ["douleur", "nutrition", "cancer", "fatigue"], pathways: ["hdj_soins_support", "hdj_douleur", "hdj_nutrition"] },
],
},
{
id: "ch_coutances",
name: "Centre Hospitalier de Coutances",
city: "Coutances",
territory: "Centre / Ouest Manche",
type: "CH",
phone: "02 33 76 50 50",
email: "secretariat.medecine@ch-coutances.fr",
hdj: [
{ type: "coordination médico-sociale", tags: ["coordination", "dac", "aidant", "isolement", "précarité"], pathways: ["hdj_coordination_sortie", "hdj_social_precarite"] },
{ type: "médecine polyvalente", tags: ["médecine", "perfusion", "traitement", "surveillance"], pathways: ["hdj_therapeutique", "hdj_post_hospit"] },
],
},
{
id: "ch_saint_hilaire",
name: "Centre Hospitalier de Saint-Hilaire-du-Harcouët",
city: "Saint-Hilaire-du-Harcouët",
territory: "Sud Manche",
type: "CH",
phone: "02 33 79 40 00",
email: "secretariat.medecine@ch-sthilaire.fr",
hdj: [
{ type: "proximité / gériatrie", tags: ["proximité", "gériatrie", "autonomie", "fragilité"], pathways: ["hdj_geriatrie", "hdj_fragilite"] },
{ type: "médecine de proximité", tags: ["perfusion", "surveillance", "post hospitalisation"], pathways: ["hdj_post_hospit", "hdj_therapeutique"] },
],
},
{
id: "ch_carentan",
name: "Centre Hospitalier de Carentan-les-Marais",
city: "Carentan",
territory: "Baie des Veys",
type: "Hôpital local",
phone: "02 33 71 60 00",
email: "accueil@ch-carentan.fr",
hdj: [
{ type: "gériatrie de proximité", tags: ["gériatrie", "proximité", "autonomie"], pathways: ["hdj_geriatrie", "hdj_fragilite"] },
],
},
{
id: "ch_gilles_buisson",
name: "Centre Hospitalier Gilles Buisson",
city: "Saint-James",
territory: "Sud Manche",
type: "Hôpital local",
phone: "02 33 89 60 00",
email: "accueil@ch-stjames.fr",
hdj: [
{ type: "gériatrie de proximité", tags: ["gériatrie", "fragilité", "autonomie"], pathways: ["hdj_geriatrie", "hdj_fragilite"] },
],
},
{
id: "hopital_simone_veil",
name: "Hôpital Simone Veil",
city: "Valognes",
territory: "Nord Cotentin",
type: "Hôpital local",
phone: "02 33 40 30 00",
email: "accueil@ch-cotentin.fr",
hdj: [
{ type: "gériatrie", tags: ["gériatrie", "fragilité", "autonomie"], pathways: ["hdj_geriatrie", "hdj_fragilite"] },
{ type: "rééducation", tags: ["rééducation", "marche", "autonomie", "post hospitalisation"], pathways: ["hdj_reeducation", "hdj_post_hospit"] },
],
},
{
id: "ch_estran",
name: "Centre Hospitalier de l’Estran",
city: "Pontorson",
territory: "Sud Manche",
type: "Hôpital local",
phone: "02 33 60 40 00",
email: "accueil@ch-estran.fr",
hdj: [
{ type: "psy adulte", tags: ["psy", "psychiatrie", "crise", "dépression", "angoisse"], pathways: ["hdj_psy_crise", "hdj_psy_transition"] },
{ type: "réhabilitation psychosociale", tags: ["réhabilitation", "psy", "isolement", "rupture suivi"], pathways: ["hdj_psy_transition"] },
],
},
{
id: "hopital_villedieu",
name: "Hôpital local de Villedieu-les-Poêles",
city: "Villedieu-les-Poêles",
territory: "Centre Manche",
type: "Hôpital local",
phone: "02 33 61 76 00",
email: "accueil@ch-villedieu.fr",
hdj: [
{ type: "gériatrie de proximité", tags: ["gériatrie", "fragilité", "autonomie", "proximité"], pathways: ["hdj_geriatrie", "hdj_fragilite"] },
],
},
];
